-- PostgreSQL version
-- Create the database manually if needed:
-- CREATE DATABASE opt_db;
-- Then connect to it:
-- \c opt_db

DROP TABLE IF EXISTS opt_orders;
DROP TABLE IF EXISTS opt_products;
DROP TABLE IF EXISTS opt_clients;

CREATE TABLE IF NOT EXISTS opt_clients (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS opt_products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_category VARCHAR(50) NOT NULL CHECK (
        product_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')
    ),
    description TEXT
);

CREATE TABLE IF NOT EXISTS opt_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    client_id UUID,
    product_id INTEGER,
    CONSTRAINT fk_opt_orders_client
        FOREIGN KEY (client_id) REFERENCES opt_clients(id),
    CONSTRAINT fk_opt_orders_product
        FOREIGN KEY (product_id) REFERENCES opt_products(product_id)
);
